name: darktable
version: git
summary: Virtual lighttable and darkroom for photographers
description: |
  Darktable is an open source photography workflow application and RAW
  developer. A virtual lighttable and darkroom for photographers. It manages
  your digital negatives in a database, lets you view them through a zoomable
  lighttable and enables you to develop raw images and enhance them.

grade: stable
confinement: strict
base: core18

apps:
  darktable:
    command: usr/bin/darktable --datadir $SNAP/usr/share/darktable --moduledir $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/darktable --configdir $SNAP_USER_DATA --localedir $SNAP/usr/share/locale
    extensions: [gnome-3-28]
    plugs:
      - opengl
      - home
      - removable-media
      - password-manager-service
      - network
      - network-bind

parts:
  darktable:
    plugin: cmake
    source: https://github.com/darktable-org/darktable/releases/download/release-3.0.0/darktable-3.0.0.tar.xz
    source-checksum: sha256/7195a5ff7ee95ab7c5a57e4e84f8c90cc4728b2c917359203c21293ab754c0db  
    configflags:
      - -DCMAKE_BUILD_TYPE=Release

      # Place the data alongside that coming from stage-packages (e.g. the lensfun database)
      - -DCMAKE_INSTALL_PREFIX=/usr

      # Support Lua scripts by way of internal Lua implementation
      - -DDONT_USE_INTERNAL_LUA=Off

      # Don't overly optimize for build CPU-- stay generic
      - -DBINARY_PACKAGE_BUILD=On

    build-packages:
      - gcc
      - g++
      - intltool
      - xsltproc
      - libgtk-3-dev
      - libxml2-utils
      - libxml2-dev
      - liblensfun-dev
      - librsvg2-dev
      - libsqlite3-dev
      - libcurl4-gnutls-dev
      - libjpeg-dev
      - libtiff5-dev
      - liblcms2-dev
      - libjson-glib-dev
      - libexiv2-dev
      - libpugixml-dev
      - libsoup2.4-dev
      - libopenexr-dev
      - libwebp-dev
      - libflickcurl-dev
      - libopenjp2-7-dev
      - libsecret-1-dev
      - libgraphicsmagick1-dev
      - libsdl1.2-dev
      - libsdl-image1.2-dev
      - libgl1-mesa-dev
      - libosmgpsmap-1.0-dev

      # Disabled capabilities for now due to interfaces:
      #
      # Camera detection/tethering/importing doesn't work, with no denials.
      # Need to investigate further before enabling this.
      # - libgphoto2-dev
      #
      # Need to test with cups-control interface
      # - libcups2-dev

      # No colord interface
      # - libcolord-dev
      # - libcolord-gtk-dev

    stage-packages:
      - libexiv2-14
      - libflickcurl0
      - libgomp1
      - libgraphicsmagick-q16-3
      - libilmbase12
      - liblensfun1
      - liblensfun-data-v1
      - libopenexr22
      - libopenjp2-7
      - libosmgpsmap-1.0-1
      - libpugixml1v5
      - libwebpmux3
      - libwmf0.2-7
      - libsecret-1-0
