name: darktable-kyrofa
version: 2.4.3snap2
summary: Virtual lighttable and darkroom for photographers
description: |
  Darktable is an open source photography workflow application and RAW
  developer. A virtual lighttable and darkroom for photographers. It manages
  your digital negatives in a database, lets you view them through a zoomable
  lighttable and enables you to develop raw images and enhance them.

grade: stable
confinement: strict

apps:
  darktable:
    command: desktop-launch darktable --datadir $SNAP/share/darktable --moduledir $SNAP/lib/darktable --configdir $SNAP_USER_DATA --localedir $SNAP/share/locale
    plugs:
      - unity7
      - x11
      - opengl
      - gsettings
      - home
      - removable-media
      - password-manager-service
      - network
      - network-bind

parts:
  darktable:
    plugin: cmake
    source: https://github.com/darktable-org/darktable/releases/download/release-2.4.3/darktable-2.4.3.tar.xz
    source-checksum: sha256/1dc5fc7bd142f4c74a5dd4706ac1dad772dfc7cd5538f033e60e3a08cfed03d3
    configflags:
      - -DCMAKE_BUILD_TYPE=Release

      # Support Lua scripts by way of internal Lua implementation
      - -DDONT_USE_INTERNAL_LUA=Off

      # Don't overly optimize for build CPU-- stay generic
      - -DBINARY_PACKAGE_BUILD=On
    build-packages:
      - gcc
      - g++
      - intltool
      - xsltproc
      - libgtk-3-dev
      - libxml2-utils
      - libxml2-dev
      - liblensfun-dev
      - librsvg2-dev
      - libsqlite3-dev
      - libcurl4-gnutls-dev
      - libjpeg-dev
      - libtiff5-dev
      - liblcms2-dev
      - libjson-glib-dev
      - libexiv2-dev
      - libpugixml-dev
      - libsoup2.4-dev
      - libopenexr-dev
      - libwebp-dev
      - libflickcurl-dev
      - libopenjpeg-dev
      - libopenjp2-7-dev
      - libsecret-1-dev
      - libgraphicsmagick1-dev
      - libsdl1.2-dev
      - libsdl-image1.2-dev
      - libgl1-mesa-dev
      - libosmgpsmap-1.0-dev

      # Disabled capabilities for now due to interfaces:
      #
      # Camera detection/tethering/importing doesn't work, with no denials.
      # Need to investigate further before enabling this.
      # - libgphoto2-dev
      #
      # Need to test with cups-control interface
      # - libcups2-dev

      # No colord interface
      # - libcolord-dev
      # - libcolord-gtk-dev

    # Stage the lensfun database used for lens correction
    stage-packages:
      - liblensfun-data

    after: [desktop-gtk3]

  desktop-gtk3:
    prime: ['*']
